---
- hosts: lb
  sudo: true
  gather_facts: no
  vars:
      web01_uri: "192.168.1.201"
      web02_uri: "192.168.1.202"
      nginx_available_dir: "/etc/nginx/sites-available"
      ngnix_service_user: root
      ngnix_service_group: root

  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: install nginx
      apt: name=nginx state=present
    - name: copy default to site-available
      template:
          src:  templates/nginx-reverse-proxy-default
          dest: "{{nginx_available_dir}}/default"
          owner: "{{ ngnix_service_user }}"
          group: "{{ ngnix_service_group }}"
          mode: 0644
    - name: restart nginx
      service: name=nginx state=restarted

- hosts: web01
  sudo: true
  gather_facts: no
  vars:
      lb_name   : lb
      web01_name: web01
      web02_name: web02
      db_name   : db
      nodejs_directory: /home/vagrant/nodejs/
      nodejs_service_user: vagrant
      nodejs_service_group: vagrant

  tasks:
   - name: update apt cache
     apt: update_cache=yes
   - name: install node before
     shell: curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
   - name: install nodejs
     apt: name=nodejs state=present
   - name: create directory
     file:  path={{nodejs_directory}} state=directory mode=0755
   - name: copy index.js
     template:
         src:  templates/web01.js
         dest: "{{nodejs_directory}}/index.js"
         owner: "{{ nodejs_service_user }}"
         group: "{{ nodejs_service_group }}"
         mode: 0640
   - name: copy package.json
     template:
          src:  templates/package.json
          dest: "{{nodejs_directory}}/package.json"
          owner: "{{ nodejs_service_user }}"
          group: "{{ nodejs_service_group }}"
          mode: 0640
   - name: install package
     shell: npm install {{nodejs_directory}}
   - name: install pm2
     shell: sudo npm install -g pm2
   - name: startup pm2
     shell: sudo pm2 startup ubuntu
   - name: copy pm2-init.sh
     template:
          src:  templates/pm2-init.d
          dest: "/etc/init.d/pm2-init.sh"
          owner: "root"
          group: "root"
          mode: 0755
   - name: run web server
     shell: bash -lc  "cd {{nodejs_directory}} && sudo npm start"

- hosts: web02
  sudo: true
  gather_facts: no
  vars:
      lb_name   : lb
      web01_name: web01
      web02_name: web02
      db_name   : db
      nodejs_directory: /home/vagrant/nodejs/
      nodejs_service_user: vagrant
      nodejs_service_group: vagrant

  tasks:
   - name: update apt cache
     apt: update_cache=yes
   - name: install node before
     shell: curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
   - name: install nodejs
     apt: name=nodejs state=present
   - name: create directory
     file: path={{nodejs_directory}} state=directory mode=0755
   - name: copy index.js
     template:
         src:  templates/web02.js
         dest: "{{nodejs_directory}}/index.js"
         owner: "{{ nodejs_service_user }}"
         group: "{{ nodejs_service_group }}"
         mode: 0640
   - name: copy package.json
     template:
          src:  templates/package.json
          dest: "{{nodejs_directory}}/package.json"
          owner: "{{ nodejs_service_user }}"
          group: "{{ nodejs_service_group }}"
          mode: 0640
   - name: install package
     shell: npm install {{nodejs_directory}}
   - name: install pm2
     shell: sudo npm install -g pm2
   - name: startup pm2
     shell: sudo pm2 startup ubuntu
   - name: copy pm2-init.sh
     template:
          src:  templates/pm2-init.d
          dest: "/etc/init.d/pm2-init.sh"
          owner: "root"
          group: "root"
          mode: 0755
   - name: run web server
     shell: bash -lc  "cd {{nodejs_directory}} && sudo npm start"

- hosts: db
  sudo: true
  sudo_user: postgres
  gather_facts: no

  vars:
    dbname: test
    dbuser: postgres
    dbpassword: 1qaz@WSX3edc

    handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted

    tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: install postgresql
      apt: name={{item}}
      with_items:
      - python-software-properties
      - software-properties-common
      - libpq-dev
      - python-psycopg2
      - postgresql-9.4
    - name: ensure database is created
      postgresql_db: name={{dbname}}
    - name: ensure user has access to database
      postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL
